version: '3'

services:

  # CouchDB backup service
  couchdb-backup:
    build: ./drive_bk
    image: ashinebourne/oolong_couchdb_bk
    volumes:
      - ./couchdb_data:/opt/couchdb/data
      - ./credentials.json:/app/credentials.json

  # CouchDB backend
  couchdb:
    image: couchdb:3.3
    restart: always
    volumes:
      - ./couchdb_data:/opt/couchdb/data
      - ./10-custom-couch-conf.ini:/opt/couchdb/etc/local.d/10-custom-couch-conf.ini

  # Oolong frontend server
  oolong-frontend:
    image: ashinebourne/oolong_front:latest
    restart: always
